// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Message struct {
	ID       int64     `json:"id"`
	UserID   int64     `json:"user_id"`
	StanzaID *string   `json:"stanza_id"`
	SentAt   time.Time `json:"sent_at"`
	Type     string    `json:"type"`
}

type MessageAttachment struct {
	ID        int64   `json:"id"`
	MessageID int64   `json:"message_id"`
	Body      *string `json:"body"`
	FileName  *string `json:"file_name"`
	FilePath  *string `json:"file_path"`
	MimeType  *string `json:"mime_type"`
	FileSize  *int64  `json:"file_size"`
}

type MessageTag struct {
	MessageID int64 `json:"message_id"`
	TagID     int64 `json:"tag_id"`
}

type SentTaggedMessage struct {
	ID                int64     `json:"id"`
	StanzaID          string    `json:"stanza_id"`
	OriginalMessageID int64     `json:"original_message_id"`
	UserID            int64     `json:"user_id"`
	SentAt            time.Time `json:"sent_at"`
}

type Tag struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

type User struct {
	ID          int64      `json:"id"`
	LID         string     `json:"l_id"`
	PhoneNumber *string    `json:"phone_number"`
	DisplayName *string    `json:"display_name"`
	CreatedAt   *time.Time `json:"created_at"`
}
