// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (user_id, stanza_id, sent_at, type)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, stanza_id, sent_at, type
`

type CreateMessageParams struct {
	UserID   int64     `json:"user_id"`
	StanzaID *string   `json:"stanza_id"`
	SentAt   time.Time `json:"sent_at"`
	Type     string    `json:"type"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.UserID,
		arg.StanzaID,
		arg.SentAt,
		arg.Type,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StanzaID,
		&i.SentAt,
		&i.Type,
	)
	return i, err
}

const createMessageAttachment = `-- name: CreateMessageAttachment :one
INSERT INTO message_attachments (message_id, body)
VALUES (?, ?)
RETURNING id, message_id, body, file_name, file_path, mime_type, file_size
`

type CreateMessageAttachmentParams struct {
	MessageID int64   `json:"message_id"`
	Body      *string `json:"body"`
}

func (q *Queries) CreateMessageAttachment(ctx context.Context, arg CreateMessageAttachmentParams) (MessageAttachment, error) {
	row := q.db.QueryRowContext(ctx, createMessageAttachment, arg.MessageID, arg.Body)
	var i MessageAttachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Body,
		&i.FileName,
		&i.FilePath,
		&i.MimeType,
		&i.FileSize,
	)
	return i, err
}

const createSentTaggedMessage = `-- name: CreateSentTaggedMessage :one
INSERT INTO sent_tagged_messages (stanza_id, original_message_id, user_id, sent_at)
VALUES (?, ?, ?, ?)
RETURNING id, stanza_id, original_message_id, user_id, sent_at
`

type CreateSentTaggedMessageParams struct {
	StanzaID          string    `json:"stanza_id"`
	OriginalMessageID int64     `json:"original_message_id"`
	UserID            int64     `json:"user_id"`
	SentAt            time.Time `json:"sent_at"`
}

func (q *Queries) CreateSentTaggedMessage(ctx context.Context, arg CreateSentTaggedMessageParams) (SentTaggedMessage, error) {
	row := q.db.QueryRowContext(ctx, createSentTaggedMessage,
		arg.StanzaID,
		arg.OriginalMessageID,
		arg.UserID,
		arg.SentAt,
	)
	var i SentTaggedMessage
	err := row.Scan(
		&i.ID,
		&i.StanzaID,
		&i.OriginalMessageID,
		&i.UserID,
		&i.SentAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (l_id, phone_number, display_name)
VALUES (?, ?, ?)
RETURNING id, l_id, phone_number, display_name, created_at
`

type CreateUserParams struct {
	LID         string  `json:"l_id"`
	PhoneNumber *string `json:"phone_number"`
	DisplayName *string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.LID, arg.PhoneNumber, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSentTaggedMessageByOriginalMessageID = `-- name: DeleteSentTaggedMessageByOriginalMessageID :exec
DELETE FROM sent_tagged_messages
WHERE original_message_id = ?
`

func (q *Queries) DeleteSentTaggedMessageByOriginalMessageID(ctx context.Context, originalMessageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSentTaggedMessageByOriginalMessageID, originalMessageID)
	return err
}

const getMessageAttachmentByMessageID = `-- name: GetMessageAttachmentByMessageID :many
SELECT id, message_id, body, file_name, file_path, mime_type, file_size FROM message_attachments
WHERE message_id = ?
`

func (q *Queries) GetMessageAttachmentByMessageID(ctx context.Context, messageID int64) ([]MessageAttachment, error) {
	rows, err := q.db.QueryContext(ctx, getMessageAttachmentByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAttachment
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Body,
			&i.FileName,
			&i.FilePath,
			&i.MimeType,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentTaggedMessageByStanzaID = `-- name: GetSentTaggedMessageByStanzaID :one
;

SELECT id, stanza_id, original_message_id, user_id, sent_at FROM sent_tagged_messages
WHERE stanza_id = ? LIMIT 1
`

func (q *Queries) GetSentTaggedMessageByStanzaID(ctx context.Context, stanzaID string) (SentTaggedMessage, error) {
	row := q.db.QueryRowContext(ctx, getSentTaggedMessageByStanzaID, stanzaID)
	var i SentTaggedMessage
	err := row.Scan(
		&i.ID,
		&i.StanzaID,
		&i.OriginalMessageID,
		&i.UserID,
		&i.SentAt,
	)
	return i, err
}

const getTagsByMessageID = `-- name: GetTagsByMessageID :many
SELECT t.id, t.user_id, t.name FROM tags t
JOIN message_tags mt ON mt.tag_id = t.id
WHERE mt.message_id = ?
`

func (q *Queries) GetTagsByMessageID(ctx context.Context, messageID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByLID = `-- name: GetUserByLID :one
SELECT id, l_id, phone_number, display_name, created_at FROM users
WHERE l_id = ? LIMIT 1
`

func (q *Queries) GetUserByLID(ctx context.Context, lID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLID, lID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByUserTag = `-- name: ListMessagesByUserTag :many
SELECT m.id, m.user_id, m.stanza_id, m.sent_at, m.type FROM messages m
JOIN message_tags mt ON mt.message_id = m.id
JOIN tags t ON t.id = mt.tag_id
WHERE t.name = ? AND t.user_id = ?
ORDER BY m.sent_at DESC
`

type ListMessagesByUserTagParams struct {
	Name   string `json:"name"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) ListMessagesByUserTag(ctx context.Context, arg ListMessagesByUserTagParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByUserTag, arg.Name, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StanzaID,
			&i.SentAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
