// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageAttachment(ctx context.Context, arg CreateMessageAttachmentParams) (MessageAttachment, error)
	CreateSentTaggedMessage(ctx context.Context, arg CreateSentTaggedMessageParams) (SentTaggedMessage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSentTaggedMessageByOriginalMessageID(ctx context.Context, originalMessageID int64) error
	GetMessageAttachmentByMessageID(ctx context.Context, messageID int64) ([]MessageAttachment, error)
	GetSentTaggedMessageByStanzaID(ctx context.Context, stanzaID string) (SentTaggedMessage, error)
	GetTagsByMessageID(ctx context.Context, messageID int64) ([]Tag, error)
	GetUserByLID(ctx context.Context, lID string) (User, error)
	ListMessagesByUserTag(ctx context.Context, arg ListMessagesByUserTagParams) ([]Message, error)
}

var _ Querier = (*Queries)(nil)
